config/routes.rb
  Rails.application.routes.draw do
  resources :fortunes do
    resources :comments, only: [:create, :destroy]
  end

  
  root 'fortunes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fortune
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
    has_many :comments
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment=Comment.new(comment_params)
    @comment.fortune_id=params[:fortune_id]
    @comment.save
    
    redirect_to fortune_path(params[:fortune_id])
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
    
    redirect_to fortune_path(params[:fortune_id])
  end
  
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  before_action :set_fortune, only: [:show, :edit, :update, :destroy]
  
  require 'open-uri'
  require 'json'

  
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
  end

  # GET /fortunes/new
  def new
    @fortune = Fortune.new
  end

  # GET /fortunes/1/edit
  def edit
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(fortune_params)

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render :show, status: :created, location: @fortune }
      else
        format.html { render :new }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fortunes/1
  # PATCH/PUT /fortunes/1.json
  def update
    respond_to do |format|
      if @fortune.update(fortune_params)
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { render :show, status: :ok, location: @fortune }
      else
        format.html { render :edit }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune.destroy
    respond_to do |format|
      format.html { redirect_to fortunes_url, notice: 'Fortune was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def update_db
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fortune
      @fortune = Fortune.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fortune_params
      params.require(:fortune).permit(:title, :rating, :image, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/fortunes/_form.html.erb
<%= form_for(@fortune) do |f| %>
  <% if @fortune.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fortune.errors.count, "error") %> prohibited this fortune from being saved:</h2>

      <ul>
      <% @fortune.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<h1>Editing Fortune</h1>

<%= render 'form' %>

<%= link_to 'Show', @fortune %> |
<%= link_to 'Back', fortunes_path %>

app/views/fortunes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fortunes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fortunes.each do |fortune| %>
      <tr>
        <td><%= fortune.title %></td>
        <td><%= fortune.rating %></td>
        <td><%= fortune.image %></td>
        <td><%= fortune.description %></td>
        <td><%= link_to 'Show', fortune %></td>
        <td><%= link_to 'Edit', edit_fortune_path(fortune) %></td>
        <td><%= link_to 'Destroy', fortune, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Fortune', new_fortune_path %>

app/views/fortunes/new.html.erb
<h1>New Fortune</h1>

<%= render 'form' %>

<%= link_to 'Back', fortunes_path %>

app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @fortune.title %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @fortune.rating %>
</p>

<p>
  <strong>Image:</strong>
  <%= @fortune.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fortune.description %>
</p>

<% @fortune.comments.each do |comment| %>
  <%= comment.content %>
  <%= link_to "destroy", fortune_comment_path(@fortune.id,comment.id), method: 'delete' %>
<% end %>

<%= form_for Comment.new, url:fortune_comments_path(@fortune.id) do |f| %>
  <%= f.label "Comment"%>
  <%= f.text_field :content %>
  <%= f.submit "go"%>
<%end%>

<%= link_to 'Edit', edit_fortune_path(@fortune) %> |
<%= link_to 'Back', fortunes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li>LOGO</li>
      <li>추천 점집</li>
      <li>가까운 점집</li>
    </ul>
  </nav>
  <%= yield %>
  <footer>Copyright(c) 2018. Asura-balbalta.</footer>
</body>
</html>